// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS_TTPUqElSXvOiTqUDMSBpSLEQMG4GDA',
    appId: '1:595723768044:web:6edddc3919b795ea22d5c9',
    messagingSenderId: '595723768044',
    projectId: 'quillai-7069d',
    authDomain: 'quillai-7069d.firebaseapp.com',
    storageBucket: 'quillai-7069d.firebasestorage.app',
    measurementId: 'G-CML9QCCD7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8WazZxsIKvCd7Up6-MrhF_8k1wIIKU0',
    appId: '1:595723768044:android:f16d767cfeb7ce9622d5c9',
    messagingSenderId: '595723768044',
    projectId: 'quillai-7069d',
    storageBucket: 'quillai-7069d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnF3XNKSPNCi2KoLqifTCA7fF5i9uu9Nc',
    appId: '1:595723768044:ios:113d5adcc44fe92822d5c9',
    messagingSenderId: '595723768044',
    projectId: 'quillai-7069d',
    storageBucket: 'quillai-7069d.firebasestorage.app',
    iosBundleId: 'com.example.quillai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnF3XNKSPNCi2KoLqifTCA7fF5i9uu9Nc',
    appId: '1:595723768044:ios:113d5adcc44fe92822d5c9',
    messagingSenderId: '595723768044',
    projectId: 'quillai-7069d',
    storageBucket: 'quillai-7069d.firebasestorage.app',
    iosBundleId: 'com.example.quillai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS_TTPUqElSXvOiTqUDMSBpSLEQMG4GDA',
    appId: '1:595723768044:web:a78f644457f855ea22d5c9',
    messagingSenderId: '595723768044',
    projectId: 'quillai-7069d',
    authDomain: 'quillai-7069d.firebaseapp.com',
    storageBucket: 'quillai-7069d.firebasestorage.app',
    measurementId: 'G-1FDPYE5TYZ',
  );

}